# -*- coding: utf-8 -*-
"""Editorial decision spec for PREMIUM GOLF TOURNAMENT.

Every (start, end) below is a HINT in seconds on the timeline; build_decisions.py
snaps each one outward/inward to real sentence boundaries from the transcript's
word-level `eos` flags, so no kept range starts or ends mid-sentence.

Story shape:
  act 0  Cold Open
  act 1  Arrival & The Speech
  act 2  Meet the Room
  act 3  On the Course with Elizabeth
  act 4  The Judo Tent
  act 5  Back Nine, Dinner & Prizes
"""

ACTS = {
    0: "Cold Open",
    1: "Arrival & The Speech",
    2: "Meet the Room",
    3: "On the Course with Elizabeth",
    4: "The Judo Tent",
    5: "Back Nine, Dinner & Prizes",
}

# (id, act, tier, start_hint, end_hint, reason)
KEEP = [
 # ---------------- ACT 0 : COLD OPEN ----------------
 ("K001", 0, "MUST", 2794, 2825,
  "Cold open: 'I hope you have insurance. And please don't sue us' then a judo throw at a golf tournament - a surprise that raises the question the video answers. Used here only, not repeated in act 4."),

 # ---------------- ACT 1 : ARRIVAL & THE SPEECH ----------------
 ("K010", 1, "MUST", 3, 19,
  "Arrival beat and the premise in one line: they are late because Kumar the mascot 'was hungry' and had to be fed bamboo. Establishes the tone immediately."),
 ("K011", 1, "OPTIONAL", 135, 146,
  "'I don't speak golf either' / 'I was getting confused between car and cart' - light personality, but the surrounding logistics are already visible on screen."),
 ("K012", 1, "SHOULD", 148, 156,
  "Sets up the speech and the nerves: 'You gotta get ready for speech here' / 'I've been practicing. I'm not great, but.'"),
 ("K013", 1, "MUST", 180, 224,
  "The plan / the public start. 'Don't like doing this' then the opening of the speech - who he is, 'I'll be taking your worst shots', and that this is Premium's first ever golf event."),
 ("K014", 1, "SHOULD", 227, 262,
  "New information the viewer needs: what Premium Group actually does, 'the biggest coordination win in our company's history', and that it is NOT a shotgun start - the problem that pays off at dinner."),
 ("K015", 1, "SHOULD", 266, 282,
  "Dinner and bragging rights are promised - sets the expectation for the final act. 'May the best team win.'"),
 ("K016", 1, "OPTIONAL", 288, 319,
  "Rules and contests. Useful information but logistics-heavy and partly re-explained at 18:05."),
 ("K017", 1, "MUST", 334, 357,
  "Plants the judo club tent at hole 12 and raffle tickets - the single line that sets up the whole centre of the video."),
 ("K018", 1, "OPTIONAL", 379, 383,
  "'Kumar is pretty cocky. It's supposed to be modest. You're a judoka.' - short mascot joke."),
 ("K019", 1, "MUST", 398, 416,
  "The honest debrief: 'I practiced that speech so much... I got lost' / 'Remi put some jokes in there and everybody's too stressed, let's just start.' Best emotional beat of the act."),
 ("K020", 1, "SHOULD", 419, 427,
  "The thing going wrong: 'Are they starting right now? We're like eight minutes late.'"),

 # ---------------- ACT 2 : MEET THE ROOM ----------------
 ("K030", 2, "MUST", 476, 508,
  "Judo athletes interview - the clean last take (the earlier take is cut per rule). Explains the club/sponsor link AND re-plants hole 12. Ends on 'They're my athletes. They're very annoying.'"),
 ("K031", 2, "OPTIONAL", 515, 522,
  "'I can mention I'm the judo coach. I don't get thrown.' - funny, but the same joke lands harder in act 4."),
 ("K032", 2, "MUST", 571, 606,
  "Why this event exists, from the founder: a small golf game for the FCC convention that 'escalated into a full blown out tournament'. The premise of the whole video."),
 ("K033", 2, "OPTIONAL", 606, 646,
  "Why connecting with clients and suppliers matters. Genuine but corporate, and said better in the dinner speech."),
 ("K034", 2, "OPTIONAL", 647, 660,
  "'Who's gonna win today?' / 'No, we're not going to win.' - nice modesty beat, expendable."),
 ("K035", 2, "SHOULD", 676, 690,
  "'Our mascot wants to fight you... it's just mascot beef, I guess.' Plants the callback that pays off at 1:04:06."),
 ("K036", 2, "OPTIONAL", 690, 705,
  "How Malcolm got hired - founded the judo club at the same time as the business. Repeated in the dinner speech."),
 ("K037", 2, "OPTIONAL", 724, 729,
  "'Takes me out of my comfort zone, which I guess is good, right?' - small honest aside."),
 ("K038", 2, "OPTIONAL", 740, 749,
  "'George, what are you doing?' / 'I'm eating candy.' - light."),
 ("K039", 2, "MUST", 762, 772,
  "Best awkward laugh in the act: 'Are you recording right now?... I'm not sure if I should answer that on camera.'"),
 ("K040", 2, "OPTIONAL", 774, 802,
  "Green Foot explains itself and the candy bar - 'everybody loves a good sugar rush halfway through the day'. Sponsor context, not story."),
 ("K041", 2, "OPTIONAL", 803, 827,
  "Yeti teddies tangent - charming but goes nowhere."),
 ("K042", 2, "OPTIONAL", 906, 912,
  "'Premium group. Built with heart.' - the clean last take of the tagline piece; earlier takes cut."),
 ("K043", 2, "OPTIONAL", 916, 931,
  "First tee shot called live - 'Right down the middle. Bit to the right. That's all right.'"),
 ("K044", 2, "SHOULD", 957, 976,
  "'There's no way I would hit a ball like that... There's just no way, I suck at it.' Sets up the celebrity shot payoff in act 3."),
 ("K045", 2, "OPTIONAL", 1000, 1018,
  "'I think you kind of messed it up' then the clean take of the piece to camera. Fun, but the same info is in the speech."),
 ("K046", 2, "OPTIONAL", 1043, 1055,
  "Clean one-line statement of the premise: an appreciation event for suppliers, clients and partners."),
 ("K047", 2, "OPTIONAL", 1085, 1097,
  "Challenges and raffle tickets restated. Third time this point is made - keep only if the earlier two are cut."),

 # ---------------- ACT 3 : ON THE COURSE WITH ELIZABETH ----------------
 ("K060", 3, "OPTIONAL", 1130, 1144,
  "'How do you say I play golf in Spanish?' - funny, but most of the exchange is not in English."),
 ("K061", 3, "SHOULD", 1181, 1204,
  "'Don't throw us into a lake, Elizabeth' plus the stained-shirt story landing on 'Premium. We care about each other.'"),
 ("K062", 3, "SHOULD", 1206, 1227,
  "The plan for the day, stated on camera: ask who's winning, who's the best player, what their connection to Premium is."),
 ("K063", 3, "OPTIONAL", 1229, 1236,
  "'I think we should have air horns' - one-line gag."),
 ("K064", 3, "OPTIONAL", 1265, 1272,
  "'In Wii Sports, they would say nice shot.'"),
 ("K065", 3, "MUST", 1281, 1317,
  "The reveal that powers the running gag: Elizabeth has never driven anything before, started learning a month ago, and is driving the cart. 'I wasn't scared before, but I am now.'"),
 ("K066", 3, "SHOULD", 1364, 1373,
  "'I think I dropped my mic. Shit. He's gonna kill me.' - genuine panic."),
 ("K067", 3, "MUST", 1459, 1467,
  "'You have that on camera? That's the first video we are gonna post. Remi messing up.' Pure vlog."),
 ("K068", 3, "MUST", 1484, 1503,
  "'Who's the best player on this team?' / 'So far, it's the trees.' plus 'We're looking for bad shots, not good shots' - the editorial premise, said out loud."),
 ("K069", 3, "OPTIONAL", 1509, 1521,
  "'Good thing they didn't ask me to play cause I've never played' / 'Elizabeth, try not to hit anybody.'"),
 ("K070", 3, "MUST", 1529, 1542,
  "Golf cart gag escalates: 'Careful. Brakes! What? I don't know how to drive.'"),
 ("K071", 3, "OPTIONAL", 1582, 1599,
  "'They'll fire you because you hit Remy' / 'I was fighting for my life, I was scared.'"),
 ("K072", 3, "OPTIONAL", 1624, 1634,
  "'Mucho is like many. My Spanish is many good.' - the joke is in English even though the subject isn't."),
 ("K073", 3, "OPTIONAL", 1636, 1642,
  "'We could get hit by a ball, that would be hilarious.'"),
 ("K074", 3, "MUST", 1655, 1688,
  "Peak of the cart gag and the best reaction in the video: 'This is a really nice golf course' straight into 'Press the brake! Keep your foot on the brake!' and 'Trust her. You're gonna survive. Just breathe.'"),
 ("K075", 3, "OPTIONAL", 1698, 1720,
  "Lindsay Construction team chat - polite, generic, no story movement."),
 ("K076", 3, "MUST", 1762, 1783,
  "Pays the gag off perfectly: 'She does everything. Without her Premium would not work... yeah, but don't trust her behind the wheel of a golf cart.'"),
 ("K077", 3, "MUST", 1785, 1796,
  "'You guys want a celeb shot?' / 'I've never played golf in my life.' - the decision that drives the next four minutes."),
 ("K078", 3, "OPTIONAL", 1812, 1831,
  "Build-up nerves before the swing - 'I'm so stressed now' / 'I only play mini.'"),
 ("K079", 3, "OPTIONAL", 1862, 1871,
  "'You're not posting this directly to Facebook, unedited?'"),
 ("K080", 3, "SHOULD", 1874, 1890,
  "'You're all looking at me, it's just stressing me out. I'm going to stretch first... I'm also like very not flexible.'"),
 ("K081", 3, "MUST", 1898, 1926,
  "The swing itself and the honest reaction: 'That was really bad.' / 'But you hit it.' / 'That was terrible.'"),
 ("K082", 3, "OPTIONAL", 1926, 1941,
  "'I hope I didn't hit anyone' plus the driving-range explanation."),
 ("K083", 3, "MUST", 1943, 1953,
  "The payoff line: 'That was really fun. What a rush. I'm gonna have to incorporate that in every tournament.'"),
 ("K084", 3, "OPTIONAL", 1989, 2018,
  "Cedar Mount client testimonial - the only outside voice on what working with Premium is actually like. Substantive but formal."),
 ("K085", 3, "OPTIONAL", 2019, 2047,
  "'You don't have to be modest' / 'I think I had some of the best drives' / 'We're keeping a real score.'"),
 ("K086", 3, "SHOULD", 2103, 2128,
  "Elizabeth on the cart: 'It's not made for a small lady like me' / 'they gave me this one' / 'because you're the boss.'"),
 ("K087", 3, "SHOULD", 2150, 2169,
  "'Just don't crash. Please.' and 'Should I be wearing a helmet? A Premium group helmet?' - gag still running."),

 # ---------------- ACT 4 : THE JUDO TENT ----------------
 ("K100", 4, "OPTIONAL", 2203, 2222,
  "Golf etiquette explained badly - 'adequate golf, adequate etiquette'."),
 ("K101", 4, "MUST", 2228, 2245,
  "'You forgot George!' / 'I don't know how to get back' / 'You guys decided to be with me?' / 'We didn't have much choice.'"),
 ("K102", 4, "OPTIONAL", 2272, 2290,
  "Malcolm on losing his French - 'my mom would know. She's like, come on Malcolm, how'd you not know this?' Warm, personal, but a tangent."),
 ("K103", 4, "MUST", 2314, 2335,
  "Elizabeth retells her own celebrity shot to the next group - 'aim left, I hit it, went right so bad onto the other field, I was so embarrassed. And they're like, at least you hit it.' A vlog telling its own story back."),
 ("K104", 4, "SHOULD", 2390, 2411,
  "The caddy joke: 'When I hit it in the woods you come back, right?' / 'I don't know how much you're paying that guy.'"),
 ("K105", 4, "OPTIONAL", 2421, 2431,
  "'What do you think of the course?' / 'The greens are furry.'"),
 ("K106", 4, "OPTIONAL", 2476, 2497,
  "Shot called live plus the 'oh shit' reaction chain."),
 ("K107", 4, "MUST", 2501, 2532,
  "The mission that structures the act: the mascot is dehydrated at hole 12 and they have to drive water to him from hole 6 - straight into 'Do I look at the front or...' / 'Look forward! Look forward!'"),
 ("K108", 4, "OPTIONAL", 2561, 2572,
  "'Don't throw the panda. Poor panda, you just get launched.'"),
 ("K109", 4, "SHOULD", 2580, 2597,
  "The challenge terms, first pass: get thrown, get three raffle tickets 'and the chiropractor' - and she's a national champion."),
 ("K110", 4, "OPTIONAL", 2611, 2622,
  "'You got three tickets. Good job.' / 'I'm not going on LinkedIn bad for this.'"),
 ("K111", 4, "OPTIONAL", 2631, 2647,
  "'The panda is a 14 year old kid... three knee surgeries.'"),
 ("K112", 4, "OPTIONAL", 2672, 2687,
  "'They were talking about us today... came up to the school in Dartmouth.'"),
 ("K113", 4, "MUST", 2705, 2724,
  "The cleanest statement of the challenge - three tickets from the girls, four from the panda. This is the version to keep."),
 ("K114", 4, "OPTIONAL", 2744, 2753,
  "The athletes pitch the challenge themselves: 'to get tickets you gotta get thrown by one of us.'"),
 ("K115", 4, "MUST", 2968, 3003,
  "The reluctance comedy: 'What's the challenge?' / 'Absolutely not.' / 'Guys, every other team did at least one.' / 'It's a soft fall.'"),
 ("K116", 4, "SHOULD", 3006, 3016,
  "'You're gonna get thrown on your back. Can't see anything.'"),
 ("K117", 4, "SHOULD", 3034, 3053,
  "The throw and the aftermath - 'You can't move. You can't see anything. Very nice. Good job.'"),
 ("K118", 4, "OPTIONAL", 3057, 3065,
  "'There's a real tall guy. Throw him hard.'"),
 ("K119", 4, "MUST", 3150, 3175,
  "'I weighed more than the two of those girls together'... then 'I'm calling in sick tomorrow. This is the worst challenge. Do it again.' Best single line in the act."),
 ("K120", 4, "MUST", 3179, 3204,
  "The thing going wrong, live: he gets thrown, and 'She wasn't filming. Help me out, motherfucker. I gotta be honest, that wasn't video.'"),
 ("K121", 4, "OPTIONAL", 3211, 3216,
  "'Give him tickets. Give him more tickets.'"),
 ("K122", 4, "OPTIONAL", 3231, 3237,
  "'This is the best challenge.'"),
 ("K123", 4, "SHOULD", 3270, 3278,
  "The running gag crystallises: 'You can't sue us. You can't sue us.'"),
 ("K124", 4, "MUST", 3307, 3332,
  "'No one's been injured yet' - immediately followed by 'Oh, I slipped. Are you all right? He's our best putter, we can't have him.' Perfect comic turn."),
 ("K125", 4, "OPTIONAL", 3434, 3443,
  "'One guy got thrown three times. Don't worry, I work with insurance, I'm not going to sue you.'"),
 ("K126", 4, "OPTIONAL", 3465, 3472,
  "'You have a choice, Kumar. Kumar loves seeing people get thrown.'"),
 ("K127", 4, "MUST", 3510, 3544,
  "The real information under the whole day: Premium sponsors Judo Canada, the Olympic team and an Olympic medallist. This is why the tent is here."),
 ("K128", 4, "OPTIONAL", 3545, 3572,
  "Judo vs BJJ, landing on 'I just tell them they're just cuddling in BJJ.'"),
 ("K129", 4, "MUST", 3584, 3593,
  "'So thank you guys. My wife throws me around better than that.' Best one-liner of the day."),
 ("K130", 4, "OPTIONAL", 3647, 3672,
  "Why the mascot throw is worth four tickets - he can't see, can't grip, and lands on top of you."),
 ("K131", 4, "SHOULD", 3682, 3704,
  "'You too scared, Elizabeth?' / 'Go! Run!' and 'I hear my bones cracking. I'm kidding, I'm kidding.'"),
 ("K132", 4, "OPTIONAL", 3742, 3758,
  "'Don't forget to take a deep breath. You also can't sue us.' then the throw."),
 ("K133", 4, "OPTIONAL", 3763, 3789,
  "'How does it feel, Eric?' plus the athletes' credentials - national champions, Canada Games medals."),
 ("K134", 4, "MUST", 3791, 3817,
  "The turn: 'Premium aren't allowed to participate' / 'We haven't had anyone from Premium get thrown' / 'Let's go. What am I doing?' The crew stops filming it and joins it."),
 ("K135", 4, "MUST", 3842, 3862,
  "Pays off 'mascot beef' from 11:16 - the Green Foot mascot called out the panda, 'and he didn't realise he was a martial artist.'"),
 ("K136", 4, "SHOULD", 3876, 3888,
  "'No tickets for the Premium guys.' / 'That really sucks.'"),
 ("K137", 4, "MUST", 3897, 3907,
  "Resolution of the cart gag: 'I'm driving now, because Elizabeth's a little too crazy behind the wheel. And we're finally safe.'"),

 # ---------------- ACT 5 : BACK NINE, DINNER & PRIZES ----------------
 ("K150", 5, "SHOULD", 3920, 3926,
  "'I'm hungry, so I'm going to drive fast.' - immediately undercuts 'we're finally safe'."),
 ("K151", 5, "OPTIONAL", 3940, 3944,
  "'Panda was fun. He did a good job.'"),
 ("K152", 5, "OPTIONAL", 3967, 3983,
  "'When I was a kid we would drive this around with five people on it' / 'At least this time we're driving in the proper direction.'"),
 ("K153", 5, "MUST", 4004, 4014,
  "'Everybody's so friendly. I don't hear any trash talk. I would talk so much shit.'"),
 ("K154", 5, "SHOULD", 4088, 4098,
  "New information the next beat needs: the chipping contest and how it pays out tickets."),
 ("K155", 5, "OPTIONAL", 4118, 4141,
  "How Parish Safety came to be here - via Elizabeth's previous job. Nice connective tissue, not essential."),
 ("K156", 5, "SHOULD", 4185, 4197,
  "'Can I try? Let's see my skills.' / 'I work for Premium, so I'm not allowed.' - the crew gets a second go at golf."),
 ("K157", 5, "OPTIONAL", 4219, 4229,
  "'Maybe if I'm good enough they'll let me play next time. I'm kidding.'"),
 ("K158", 5, "MUST", 4233, 4255,
  "The chipping attempt heckled in real time: 'That was bad. Come on, George. Too high. You have to get the shot that I got.'"),
 ("K159", 5, "MUST", 4286, 4303,
  "Lands the whole running thread of the crew being terrible at golf: 'That was bad. That was also bad. Let's try again. See, I'm not a golfer.'"),
 ("K160", 5, "MUST", 4465, 4499,
  "Dinner speech opens by paying off act 1's problem: 'we thought we were going to have a shotgun. And guess what? We didn't. Thanks to the team for having reacted that fast.'"),
 # Same problem as K163-K166: the end hint here reached past a 6.6s applause gap,
 # so these two rows abutted and played as one 88s block. Split at the applause.
 ("K161", 5, "MUST", 4501.96, 4550.88,
  "The origin story told back to the room - 'mind if I organise a game of golf with a few friends' turning into a tournament of more than eight people. Ends on 'Thank you, Jeremiah' into applause."),
 ("K162", 5, "SHOULD", 4557.44, 4589.56,
  "'That describes us very well at Premium' - the same escalation applied to the business, from one division to caulking, fireproofing and drywall across six provinces."),
 # K163-K166 were four rows that abutted exactly, so phase 2 played them as one
 # unbroken 114s block. Split into four beats at the only boundaries the audio
 # actually offers: a 6.4s applause gap, a 5.3s gap, and the single 400ms pause
 # in the middle of the speech. Everything between 01:17:49 and 01:18:26 is
 # continuous - no inter-sentence gap there is wider than 140ms - so the cuts
 # below are the only ones available without slicing into a word.
 ("K163", 5, "MUST", 4597.44, 4616.44,
  "Genuine news, announced live: the Ottawa division's first year and last week's Montreal acquisition, buttoned with 'Thank you'. Ends into applause."),
 ("K164", 5, "SHOULD", 4622.84, 4629.56,
  "Short callback to act 4 from the podium: 'You also got to see my judo team here today. Who got thrown around a little bit.' Deliberately brief between two longer blocks."),
 ("K165", 5, "SHOULD", 4643.72, 4679.16,
  "'Judo is a big, big part of who I am, and what happened to me in the past' - the personal version of what act 4 discovered on the course, through Judo Canada, Jessica Clinch and the Otoshi club with Malcolm."),
 ("K166", 5, "MUST", 4685.21, 4711.24,
  "The emotional core: sponsoring Judo Quebec, and why - 'helping kids, giving them a way of life and keeping them out of the streets, something very close to my heart.'"),
 ("K167", 5, "MUST", 4718, 4727,
  "'I hope that this tournament is going to become an annual tournament.' The forward-looking beat."),
 ("K168", 5, "MUST", 4752, 4787,
  "The thesis of the whole event: 'If I have 100 clients, no employees, I can't do nothing. If I have 100 employees with no clients, I can't do nothing. So for me, they both come first.'"),
 ("K169", 5, "OPTIONAL", 4798, 4820,
  "'The employees, they don't work for us. We work for them.' Strong, but it restates the line above."),
 ("K170", 5, "SHOULD", 4833, 4851,
  "Closes the speech: 'Nice cause, nice weather and great people. Thank you very much.'"),
 ("K171", 5, "OPTIONAL", 4865, 4873,
  "'Everyone's a winner. You all get a participation trophy. I'm just kidding.'"),
 ("K172", 5, "OPTIONAL", 4882, 4920,
  "The sponsor thank-you list. Necessary for the client, but it is a list."),
 ("K173", 5, "OPTIONAL", 4927, 4944,
  "First prize handed out, plus 'Sorry, I wasn't sure - it's the handwriting.'"),
 ("K174", 5, "OPTIONAL", 4957, 4966,
  "'Whoa whoa whoa, sorry, I'm ruining your setup.'"),
 ("K175", 5, "OPTIONAL", 4966, 4985,
  "Closest to the pin at 13, plus 'There's a lunch in there. I'm kidding, I don't know what's in there.'"),
 ("K176", 5, "OPTIONAL", 5018, 5032,
  "The winner refusing the donated prize and taking the hat instead."),
 ("K177", 5, "SHOULD", 5035, 5056,
  "Same guy wins twice: 'You want a second hat?... You want a second cooler? At least give it to your buddy next door.'"),
 # Third instance of the same thing: the end hint reached past a 3.0s applause
 # gap, merging these into one 51s block. Split at the applause.
 ("K178", 5, "MUST", 5061.51, 5081.91,
  "The payoff the whole day has been asking about - the winning team announced, ending on 'Congratulations' into applause."),
 ("K179", 5, "MUST", 5086.75, 5111,
  "'Seven strokes better than the second best.' / 'I don't know what that means.' / 'That's just bragging rights.' / 'No, you guys don't win a prize.'"),
 ("K180", 5, "OPTIONAL", 5135, 5153,
  "The raffle begins - what's in the first prize, 'I'll pick a ticket, I won't look, I promise.'"),
 ("K181", 5, "OPTIONAL", 5161, 5176,
  "First raffle number drawn and claimed."),
 ("K182", 5, "SHOULD", 5379, 5400,
  "Big prize reaction: 'That was coming.' / 'Good job, you got a TV?'"),
 ("K183", 5, "MUST", 5434, 5444,
  "The most genuine reaction of the night: 'No way! You rats!'"),
 ("K184", 5, "OPTIONAL", 5529, 5541,
  "'Dave, you can't win by that... they're not mine.' / 'You were so heavily invested.'"),
 ("K185", 5, "SHOULD", 5575, 5581,
  "'I think no one wants this cooler, man.'"),
 ("K186", 5, "SHOULD", 5594, 5604,
  "Payoff of the cooler gag: 'You didn't want it. Now you have it.' / 'I'll give it to someone.'"),
 ("K187", 5, "OPTIONAL", 5631, 5635,
  "'You gotta draw four times for a lunch box.'"),
 ("K188", 5, "MUST", 5707, 5738,
  "The grand prize - a heat pump from Green Foot, introduced by the sponsor who was interviewed back in act 2."),
 ("K189", 5, "OPTIONAL", 5747, 5760,
  "The grand prize number read out."),
 ("K190", 5, "MUST", 5772, 5778,
  "'Everyone's gonna hate this guy.' The button on the raffle."),
 ("K191", 5, "SHOULD", 5786, 5802,
  "The reflection at the end: 'You're tired.' / 'I gotta go. My team.' Quiet close on a long day."),
]

# (id, act, start_hint, end_hint, reason) - the big drops, so the shape is visible
CUTS = [
 ("X001", 1, 19, 134,  "Arrival logistics with course staff - where to park, which cart, how to reach hole 12. All of it is visible on screen or re-explained in the speech."),
 ("X002", 1, 156, 179, "Dead air and crosstalk while the speech is being found. Nothing said."),
 ("X003", 1, 357, 378, "Post-speech crosstalk, no story movement."),
 ("X004", 1, 383, 397, "Crosstalk between the mascot joke and the speech debrief."),
 ("X005", 2, 427, 475, "First take of the judo athlete interview - aborted on camera with 'Retake, retake'. Keeping the clean last take at 7:56."),
 ("X006", 2, 522, 570, "Pre-interview setup and negotiating the question order. Setup already explained."),
 ("X007", 2, 705, 723, "Small talk about following each other on social media. Tangent, no connection to the premise."),
 ("X008", 2, 827, 905, "LinkedIn tangent, then three repeated attempts at the 'Glen Arbor / Premium group' B-roll line. Keeping only the last take."),
 ("X009", 2, 976, 999, "First flubbed take of the piece to camera, immediately redone."),
 ("X010", 2, 1055, 1084, "Re-negotiating on camera how to phrase the raffle explanation - the answer that follows is the one to keep."),
 ("X011", 3, 1097, 1129, "Spanish-language interview bit. Not in English."),
 ("X012", 3, 1144, 1180, "Continuation of the Spanish bit. Not in English."),
 ("X013", 3, 1373, 1458, "Raffle-ticket logistics over the phone - who has the tickets, which hole. Pure admin."),
 ("X014", 3, 2047, 2102, "Fragmented crosstalk and an off-topic complaint about another organisation. Does not connect to the premise."),
 ("X015", 4, 2290, 2313, "Crosstalk while driving between groups."),
 ("X016", 4, 2825, 2967, "French-language interview and repeated throw cycles with no new dialogue beat. Not in English / already covered."),
 ("X017", 4, 3065, 3149, "More throw cycles with thin dialogue - the same beat as 49:28 and 52:30."),
 ("X018", 4, 3332, 3433, "Further repeated throws. The 'no one's been injured yet' turn already did this better."),
 ("X019", 5, 4303, 4464, "Dice game and an extended technical tangent on intumescent paint and spray machines. Does not move the story."),
 ("X020", 5, 5176, 5378, "Long stretch of raffle numbers being read out and claimed. Repetitive - keeping only the reactions that land."),
 ("X021", 5, 5444, 5528, "More raffle number reading."),
 ("X022", 5, 5604, 5706, "More raffle number reading, up to the grand prize."),
 ("X027", 5, 5081.91, 5086.75, "Applause after the winning team is announced, plus a stray 'Oh yeah'. Trimmed so the announcement and the score reveal are two segments."),
 ("X026", 5, 4550.88, 4557.44, "Applause after the thank-you to Jeremiah. Trimmed so the origin story and the 'that describes us very well' beat become two segments instead of one 88s block."),
 ("X023", 5, 4616.44, 4622.84, "Applause after the acquisition announcement. Good sound, but 6.4s of it is a hole - trimmed to make the cut into the judo callback."),
 ("X024", 5, 4629.56, 4643.72, "'There you go. Here you go. Thank you. Very gentle. Never hurt me that.' - fragmentary handover chatter with two dead pauses inside it."),
 ("X025", 5, 4679.16, 4685.21, "'I'm the founder of the club' is the fourth time that is said (45:31, 58:36, 1:02:13), and 'pretty, pretty, pretty close' is a stumble on the same point 'very close to my heart' makes better ten seconds later."),
]
